-- 员工聚合保留业务版本和安全版本；安全版本变化会立即使旧会话失效。
CREATE TABLE identity_employee (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(32) NOT NULL UNIQUE,
    name VARCHAR(50) NOT NULL,
    phone VARCHAR(11) NOT NULL DEFAULT '',
    sex CHAR(1) NOT NULL DEFAULT '2' CHECK (sex IN ('0', '1', '2')),
    id_number VARCHAR(18) NOT NULL DEFAULT '',
    password_hash VARCHAR(100) NOT NULL,
    role VARCHAR(16) NOT NULL CHECK (role IN ('ADMIN', 'STAFF')),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    security_version BIGINT NOT NULL DEFAULT 0,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CHECK (role <> 'ADMIN' OR enabled)
);
-- P1 仅由初始化流程配置一个管理员，其他账号均为普通员工。
CREATE UNIQUE INDEX identity_single_administrator_idx ON identity_employee (role)
    WHERE role = 'ADMIN';

-- 原始令牌只在登录响应中返回；数据库仅保存 SHA-256 摘要。
CREATE TABLE identity_session (
    token_hash CHAR(64) PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES identity_employee (id),
    security_version BIGINT NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX identity_session_employee_idx ON identity_session (employee_id);
CREATE INDEX identity_session_expiry_idx ON identity_session (expires_at);

-- 审计只记录固定动作与结果及内部标识，不记录密码、令牌、姓名、电话或身份证。
CREATE TABLE identity_audit (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    action VARCHAR(40) NOT NULL,
    outcome VARCHAR(16) NOT NULL,
    actor_id BIGINT,
    subject_id BIGINT,
    occurred_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX identity_audit_time_idx ON identity_audit (occurred_at);
